// <auto-generated />
using System;
using BlackHoleSim.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BlackHoleSim.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260815064410_AddRenderJobOwner")]
    partial class AddRenderJobOwner
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BlackHoleSim.Api.Data.RenderJobEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<string>("OwnerId")
                        .HasColumnType("text");

                    b.Property<byte[]>("Png")
                        .HasColumnType("bytea");

                    b.Property<double>("Progress")
                        .HasColumnType("double precision");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Status");

                    b.HasIndex("OwnerId", "CreatedAt");

                    b.ToTable("RenderJobs");
                });

            modelBuilder.Entity("BlackHoleSim.Api.Data.RenderJobEntity", b =>
                {
                    b.OwnsOne("BlackHoleSim.Shared.RenderParameters", "Parameters", b1 =>
                        {
                            b1.Property<Guid>("RenderJobEntityId")
                                .HasColumnType("uuid");

                            b1.Property<double>("BMax")
                                .HasColumnType("double precision");

                            b1.Property<int>("Height")
                                .HasColumnType("integer");

                            b1.Property<int>("MaxSteps")
                                .HasColumnType("integer");

                            b1.Property<double>("Rcam")
                                .HasColumnType("double precision");

                            b1.Property<double>("Rin")
                                .HasColumnType("double precision");

                            b1.Property<double>("Rout")
                                .HasColumnType("double precision");

                            b1.Property<double>("Step")
                                .HasColumnType("double precision");

                            b1.Property<int>("Width")
                                .HasColumnType("integer");

                            b1.HasKey("RenderJobEntityId");

                            b1.ToTable("RenderJobs");

                            b1
                                .ToJson("Parameters")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("RenderJobEntityId");
                        });

                    b.Navigation("Parameters")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
